### ISSUE TITLE
How do I make a keystore file?

### ISSUE THREAD

**Issue by SteadyAction** [BANKEX/web3swift#279]
How do I make a keystore file?
I used keystore V3 object and use its `data`, and then converted it to JSON file.
It looks like a fine Keystore file but actually it can't be imported by other wallets like MyEtherWallet

**Comment by v57** [comment]
I'll check and back to you

**Comment by v57** [comment]
Okay i created test json file using:
```
let privateKey = "39c17117ae3d57c564791af01163e2fd5e25cc221a55017bd5559bc7acd23b86".hex
print(try! EthereumKeystoreV3(privateKey: privateKey, password: "SomePassword")!.serialize()!.string)
```

here is my json file:
```
{
  "version" : 3,
  "id" : "ce38d533-9108-4d34-8d08-23dddc21a791",
  "crypto" : {
    "ciphertext" : "9e5519db5db8846dc6fc25ee00fa29e52125fce7cbd12e89ea746d9f8fe5e0ba",
    "cipherparams" : {
      "iv" : "f71fd3cf6d9a8227f16949d57e17a327"
    },
    "kdf" : "scrypt",
    "kdfparams" : {
      "r" : 6,
      "p" : 1,
      "n" : 4096,
      "dklen" : 32,
      "salt" : "450f9a6cbbe9272ad19b6ad550a40c808ca73eef7dd6d54aaf77870570828d31"
    },
    "mac" : "482315b6ebb030a280ea77c7242328fa2c60da8f3dfe12ac77ee28f10df7f1fd",
    "cipher" : "aes-128-cbc"
  },
  "address" : "0x9a2c72150c4fc3c86de8ecf0092a02e35d2843fd"
}
```

I tried to import this file from myetherwallet and it gives me this errror.
<img width="562" alt="screenshot 2019-02-12 at 12 10 28" src="https://user-images.githubusercontent.com/2669441/52624335-941bec80-2ebf-11e9-9b8e-1d868d019770.png">

I look further and find that when i create wallet in myetherwallet "by keystore file"
https://www.myetherwallet.com/create-wallet
<img width="615" alt="screenshot 2019-02-12 at 12 14 55" src="https://user-images.githubusercontent.com/2669441/52624443-d7765b00-2ebf-11e9-83d4-fb3fc2e27fd6.png">

I got the same error:
<img width="594" alt="screenshot 2019-02-12 at 12 09 49" src="https://user-images.githubusercontent.com/2669441/52624506-ee1cb200-2ebf-11e9-8415-1c394fe0e080.png">

So looks like its myetherwallet bug. 

KeystoreV3 uses this format: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

**Comment by SteadyAction** [comment]
@v57  no it's not.
Try other wallets. They give same error as well.
https://github.com/MyEtherWallet/MyEtherWallet/issues/411#issuecomment-453238885

This is what I got from MEW

**Comment by v57** [comment]
You can change aes mode but this still doesn't works
```
EthereumKeystoreV3(privateKey: privateKey, password: "SomePassword", aesMode: "aes-128-ctr")
```

```
{
    "version" : 3,
    "id" : "474e19ff-bd9e-4bee-93e0-62118184e0c2",
    "crypto" : {
        "ciphertext" : "627285333fc8d875bbc5ddc7abf81fdc4c9f18295d3c72d2e3b2f2b4460ceaa5",
        "cipherparams" : {
            "iv" : "9fec66b4d0c6368e470f792578ee7f77"
        },
        "kdf" : "scrypt",
        "kdfparams" : {
            "r" : 6,
            "p" : 1,
            "n" : 4096,
            "dklen" : 32,
            "salt" : "9241b994cff02dcb6da3523a3f8b2e6db88d95ee13bbe4c71112f3613b18047d"
        },
        "mac" : "763cc96af6c49b7d4eae0bd69ddafb5e5b5e59898170aa15059d2b59b7cad10d",
        "cipher" : "aes-128-ctr"
    },
    "address" : "0x9a2c72150c4fc3c86de8ecf0092a02e35d2843fd"
}
```

**Comment by SteadyAction** [comment]
@v57 if you try on chrome extension MEW or Web version, it will give you more clue.
And it works well if I make a new wallet using MEW -> get keystore -> import the keystore with password.
But not with the keystore I made using web3Swift :(

**Comment by v57** [comment]
I found that address in web3swift stores with 0x prefix and other keystores don't. I will fix that and make an update in 5 minutes

web3swift keystore:
```
{
  "version" : 3,
  "id" : "90a519d7-d904-41f8-984a-f89df29c2fd5",
  "crypto" : {
    "ciphertext" : "7a2c65b70fbeb4e64de1ec30beab912ba91916096929d9e9acbb342691c8c145",
    "cipherparams" : {
      "iv" : "e5a68a8726435f209217d922886734ce"
    },
    "kdf" : "scrypt",
    "kdfparams" : {
      "r" : 6,
      "p" : 1,
      "n" : 4096,
      "dklen" : 32,
      "salt" : "91ed40d16d7fed9d6e0a1c1f95e86ce4d9af3133487132c582cc0b63cecdc185"
    },
    "mac" : "077dd4f5ed3bbf323ef231fa9aecfd851b4bfabe9d9e4ffb9cfd5385b8299fc1",
    "cipher" : "aes-128-ctr"
  },
  "address" : "0x9a2c72150c4fc3c86de8ecf0092a02e35d2843fd"
}
```

geth keystore:
```
{
  "version" : 3,
  "id" : "59878f79-90a9-486f-84f2-53d8ad3ae0ff",
  "crypto" : {
    "ciphertext" : "81342f3b03c7017fe60d1a0011fb638602e7ea484ebe133ddf16b42cef07bd52",
    "cipherparams" : {
      "iv" : "ec20e507822a3079cb44d8fdc10debd9"
    },
    "kdf" : "scrypt",
    "kdfparams" : {
      "r" : 8,
      "p" : 1,
      "n" : 262144,
      "dklen" : 32,
      "salt" : "58b8f612eadb75b9009db1f12392491ed3f6eaddd92aaa7467c1c6018337ef77"
    },
    "mac" : "405528ae469b0ef8103508f75e99178d555cacb947a422ec9ff4e430121852de",
    "cipher" : "aes-128-ctr"
  },
  "address" : "4619617d35e8d1d85dfecc6d664f7af7e14a4236"
}
```

**Comment by SteadyAction** [comment]
@v57 but does that fix the problem?

**Comment by v57** [comment]
Yes

**Comment by kvhnuke** [comment]
Cant find worker seems like a MEW error, can you let me know what browser you use, you can also use vintage.myetherwallet.com to test

**Comment by v57** [comment]
@krboktv i'm using safari

**Comment by v57** [comment]
@SteadyAction Okay should work now. Update your pods

**Comment by SteadyAction** [comment]
@v57 
It still doesn't work with BIP32Keystore. Have you tried with BIP32Keystore?
If it works for you, can show me your example code using BIP32Keystore? 
Maybe I am doing it wrong.

**Comment by v57** [comment]
There are no standards for BIP32 keystore json file. Because it contains multiple addresses with different paths you cannot use it in other wallets. You can convert it to keystore v3 then export.

**Comment by v57** [comment]
So this should work:
```
let password = "some"
let keystore = try BIP32Keystore(mnemonics: Mnemonics(), password: password)
let privateKey = try keystore.UNSAFE_getPrivateKeyData(password: password, account: keystore.addresses[0])
let json = try EthereumKeystoreV3(privateKey: privateKey, password: password)!.serialize()
```

**Comment by SteadyAction** [comment]
@v57 
well... it's still not working

```
{
  "version" : 3,
  "id" : "ce38d533-9108-4d34-8d08-23dddc21a791",
  "crypto" : {
    "ciphertext" : "9e5519db5db8846dc6fc25ee00fa29e52125fce7cbd12e89ea746d9f8fe5e0ba",
    "cipherparams" : {
      "iv" : "f71fd3cf6d9a8227f16949d57e17a327"
    },
    "kdf" : "scrypt",
    "kdfparams" : {
      "r" : 6,
      "p" : 1,
      "n" : 4096,
      "dklen" : 32,
      "salt" : "450f9a6cbbe9272ad19b6ad550a40c808ca73eef7dd6d54aaf77870570828d31"
    },
    "mac" : "482315b6ebb030a280ea77c7242328fa2c60da8f3dfe12ac77ee28f10df7f1fd",
    "cipher" : "aes-128-cbc"
  },
  "address" : "9a2c72150c4fc3c86de8ecf0092a02e35d2843fd"
}
```

This is what you generated. I saved this file as json file. I tried to import this keystore on MEW and Metamask. All of them said "unable to decrypt data"

This is really weird. Please help

**Comment by v57** [comment]
Because its encrypted in aes-128-ctr. Not aes-128-cbc

```
{
  "version" : 3,
  "id" : "90a519d7-d904-41f8-984a-f89df29c2fd5",
  "crypto" : {
    "ciphertext" : "7a2c65b70fbeb4e64de1ec30beab912ba91916096929d9e9acbb342691c8c145",
    "cipherparams" : {
      "iv" : "e5a68a8726435f209217d922886734ce"
    },
    "kdf" : "scrypt",
    "kdfparams" : {
      "r" : 6,
      "p" : 1,
      "n" : 4096,
      "dklen" : 32,
      "salt" : "91ed40d16d7fed9d6e0a1c1f95e86ce4d9af3133487132c582cc0b63cecdc185"
    },
    "mac" : "077dd4f5ed3bbf323ef231fa9aecfd851b4bfabe9d9e4ffb9cfd5385b8299fc1",
    "cipher" : "aes-128-ctr"
  },
  "address" : "9a2c72150c4fc3c86de8ecf0092a02e35d2843fd"
}
```

**Comment by SteadyAction** [comment]
then how do I export Keystore that can be imported in MEW/Metamask?
How do i make my keystore encryted in aes1280cbc?

**Comment by SteadyAction** [comment]
I am using EthereumV3

**Comment by v57** [comment]
MyEtherWallet works fine with aes-128-ctr mode. Also geth uses `aes-128-ctr` mode too.

**Comment by v57** [comment]
web3swift uses aes128cbc mode by default

**Comment by v57** [comment]
```
let privateKey = "39c17117ae3d57c564791af01163e2fd5e25cc221a55017bd5559bc7acd23b86".hex
print(try! EthereumKeystoreV3(privateKey: privateKey, password: "SomePassword")!.serialize()!.string)
```

Should return

```
{
  "version" : 3,
  "id" : "ce38d533-9108-4d34-8d08-23dddc21a791",
  "crypto" : {
    "ciphertext" : "9e5519db5db8846dc6fc25ee00fa29e52125fce7cbd12e89ea746d9f8fe5e0ba",
    "cipherparams" : {
      "iv" : "f71fd3cf6d9a8227f16949d57e17a327"
    },
    "kdf" : "scrypt",
    "kdfparams" : {
      "r" : 6,
      "p" : 1,
      "n" : 4096,
      "dklen" : 32,
      "salt" : "450f9a6cbbe9272ad19b6ad550a40c808ca73eef7dd6d54aaf77870570828d31"
    },
    "mac" : "482315b6ebb030a280ea77c7242328fa2c60da8f3dfe12ac77ee28f10df7f1fd",
    "cipher" : "aes-128-cbc"
  },
  "address" : "9a2c72150c4fc3c86de8ecf0092a02e35d2843fd"
}
```

**Comment by SteadyAction** [comment]
SOLVED thanks
